### ISSUE TITLE
some questions about this codes

### ISSUE THREAD

**Issue by 123-mzr** [APMonitor/applications#1]
Hi, I am Meng Zhuoran, a master student of China University of Petroleum(Beijing). I download this codes and open "drilling_and_hydraulics" and run "drilling.m". I found the following errors:

</pre>
Dynamic Optimization --------------
apm 202.204.205.211_drill <br><pre> ----------------------------------------------------------------
 APMonitor, Version 0.9.2
 APMonitor Optimization Suite
 ----------------------------------------------------------------
 
 @error: Unspecified Time
 apm_dyn_model_init_a error: time unspecified in csv file
   action: add a column with header "time" to csv file
           or turn OFF csv_read in configuration
 STOPPING...
</pre>

and 

y = z.x errors

Could you tell me how to solve it? Thanks a lot

**Comment by APMonitor** [comment]
Here is the code in Python that is working correctly: https://github.com/APMonitor/drilling  Do you need to use MATLAB or is Python okay?

**Comment by 123-mzr** [comment]
I use MATLABR2017b and python 3.7. But I download this codes:  https://github.com/APMonitor/applications. Is this the correct code? Thanks a lot

**Comment by APMonitor** [comment]
The code was old and wasn't compatible with the latest version of APM MATLAB or APM Python. I have updated the code and now it works with the latest versions. https://github.com/APMonitor/applications/tree/master/drillstring_and_hydraulics  There are also other models and more description here: https://github.com/APMonitor/drilling
